### ISSUE TITLE
Wrong line displayed on logs

### ISSUE THREAD

**Issue by alexo310** [Blob2763/easydebugger#1]
I've noticed this when testing my code (which uses A LOT of functions) that, when a message/log appears it says the wrong line. Let me explain:

so imagine this is my main script
```
from .otherScript import *

def main():
    otherFunction()

if __name__ == "__main__":
    main()

```

and this is otherScript.py
```
import easydebugger as ed

def otherFunction():
    ed.error('error')
```

when the error message appears, it shows the line where the main() function was called, instead of the line where the error message was called. I may test this again to see if it's just with functions from other scripts.

**Comment by Blob2763** [comment]
fixed :) if you update the library using `pip install --upgrade easydebugger` everything should now work

**Comment by alexo310** [comment]
hi! i've noticed there's an error with the code now but I know how to fix it. Specifically with the variable caller_line_number.

The variable is declared in the script like this:
`caller_line_number = inspect.stack()[2].lineno`
When it should be like this:
`caller_line_number = inspect.stack()[1].lineno`

Basically, what changed is the index.

**Comment by Blob2763** [comment]
you're right! it should be fixed now if you update
