### ISSUE TITLE
Make colour codes on ed.display_message() work

### ISSUE THREAD

**Issue by alexo310** [Blob2763/easydebugger#2]
So this bug is already acknowledged, but I'm still going to explain it.

When I put an integer (number) in the colour_code argument it will not do anything since the function wants a string to be received. There's one way to fix this which is with the python function - isinstance() - which is explained below.
```py
isinstance(value, type)
# value can be an integer, boolean, float or string. it does accept variables
# type can be int, bool, float, str
```

The isinstance function returns a boolean which is useful for conditions
```py
print(isinstance('hello!', str))
# True

print(isinstance(True, int))
# False
```

In this case, we can use that function to convert the number given in the colour_code argument to a string without any errors:
```py
if isinstance(colour_code, int):
    colour_code = str(colour_code)
```

Note: this can also be achieved by just using the str() function but I find the isinstance function better for some situations.

**Comment by Blob2763** [comment]
Should be fixed now :)
