### ISSUE TITLE
Info log and recall custom log

### ISSUE THREAD

**Issue by daniel4-scratch** [Blob2763/easydebugger#3]
Add an info log that would be blue with an "i" icon

And be able to easily recall custom display logs.
```python
log = ed.new_log(my custom log data)

log("hello") 
#or
log.log("hi")

```

Made this on phone, i can elaborate more when i have access to my pc

**Comment by Blob2763** [comment]
What would the log data look like? What would log.log() do?

**Comment by daniel4-scratch** [comment]
its just a [custom message](https://github.com/Blob2763/easydebugger?tab=readme-ov-file#custom-messages) but re-callable
```python
my_message = ed.display_message("^", "LABEL", 123, "65")

my_message("message")
```
expected result:
`^ LABEL message (line 123)`

##### sorry i made this issue on my phone, i hate phone keyboards XD

**Comment by Blob2763** [comment]
added! documentation coming soon :)
